services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /data/audiobooks:/audiobooks
      - /data/podcasts:/podcasts
      - /data/metadata:/metadata
      - /data/config:/config
    restart: unless-stopped
networks:
  nginxpm:
    external: true